FROM mariadb:10.5.13
ADD ./setup.sh /docker-entrypoint-initdb.d
ENV MYSQL_ROOT_PASSWORD NigelGerald454
#ENV MARIADB_USER=wpuser \
    #MARIADB_PASSWORD=bruh \
    #MARIADB_ROOT_PASSWORD=NigelGerald454 \
    #MARIADB_USER=drupaluser \
    #MARIADB_PASSWORD=drewpeacock
#docker build --rm -t prod .
